import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <div>
          <header className="m-[2rem] rounded-lg border border-[#1E2D3D] bg-[#011627]">
            {" "}
            <Nav />
          </header>
          <div className="content mt-[7rem] mx-[6.1rem]  border border-[#1E2D3D] bg-[#011627]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
