import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <header className="m-[2rem] rounded-lg border border-[#1E2D3D] bg-[#011627]">
            {" "}
            <Nav />
          </header>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
